# Generated by Django 3.0.3 on 2020-02-28 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultConsumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Value')),
                ('item', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Item', verbose_name='Item')),
                ('session_type', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='core.SessionType', verbose_name='Session type')),
            ],
        ),
    ]
