# Generated by Django 3.0.3 on 2020-02-28 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0002_record_used_coupon'),
        ('warehouse', '0002_defaultconsumable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Value')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('item', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='used_as_consumables', to='warehouse.Item', verbose_name='Item')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='records.Record', verbose_name='Record')),
            ],
        ),
    ]
