# Generated by Django 3.0.3 on 2020-02-28 14:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('warehouse', '0003_consumable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultconsumable',
            name='session_type',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='default_consumables', to='core.SessionType', verbose_name='Session type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0))], verbose_name='Цена закупки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0))], verbose_name='Цена продажи'),
        ),
    ]
