# Generated by Django 3.0.3 on 2020-02-28 14:55

from decimal import Decimal
import django.core.validators
from django.db import migrations
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20200228_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purchase_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0, currency='UAH'))], verbose_name='Цена закупки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0, currency='UAH'))], verbose_name='Цена продажи'),
        ),
    ]
