# Generated by Django 3.0.3 on 2020-03-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20200302_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='defaultconsumable',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Value'),
        ),
    ]
