# Generated by Django 3.0.3 on 2020-03-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20200309_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='value_currency',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Value'),
        ),
    ]
