# Generated by Django 3.0.3 on 2020-03-10 09:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20200310_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='defaultconsumable',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0.01, currency='UAH'))], verbose_name='Цена закупки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0.01, currency='UAH'))], verbose_name='Цена продажи'),
        ),
    ]
