# Generated by Django 3.0.3 on 2020-02-28 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20200228_1216'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parlors', '0001_initial'),
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('new', 'New'), ('pending', 'Pending'), ('in_work', 'In work'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='new', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('approximate_time', models.TimeField(blank=True, null=True, verbose_name='Approximate time')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('sketch', models.ImageField(blank=True, null=True, upload_to='records/sketches', verbose_name='Sketch')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('UAH', 'UAH ₴')], default='UAH', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Price')),
                ('created_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='customers.Customer', verbose_name='Customer')),
                ('parlor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='parlors.Parlor', verbose_name='Parlor')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='Performer')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.SessionType', verbose_name='Record type')),
            ],
            options={
                'verbose_name': 'record',
                'verbose_name_plural': 'records',
                'permissions': (('can_change_session_time', 'Can change session time'), ('can_cancel_session', 'Can cancel session'), ('can_start_session', 'Can start session'), ('can_finish_session', 'Can finish session')),
            },
        ),
        migrations.CreateModel(
            name='Prepayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('value_currency', djmoney.models.fields.CurrencyField(choices=[('UAH', 'UAH ₴')], default='UAH', editable=False, max_length=3)),
                ('value', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Value')),
                ('created_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prepayments', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepayments', to='records.Record', verbose_name='Record')),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prepayments', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'prepayment',
                'verbose_name_plural': 'prepayments',
                'permissions': (('can_cancel_prepayment', 'Can cancel prepayment'),),
            },
        ),
        migrations.CreateModel(
            name='EmployeeRecordPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('invite', 'Invite'), ('work', 'Work')], max_length=10, verbose_name='Type')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('UAH', 'UAH ₴')], default='UAH', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Amount')),
                ('employee', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='record_payments', to='accounts.Profile', verbose_name='Employee')),
                ('record', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='employee_payments', to='records.Record', verbose_name='Record')),
            ],
            options={
                'verbose_name': 'employee record payment',
                'verbose_name_plural': 'employee record payments',
                'unique_together': {('type', 'record')},
            },
        ),
    ]
