# Generated by Django 3.0.3 on 2020-03-02 09:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200228_1216'),
        ('records', '0002_record_used_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepayment',
            name='value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0, currency='UAH'))], verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='record',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='accounts.Profile', verbose_name='Performer'),
        ),
    ]
