# Generated by Django 3.0.3 on 2020-03-02 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20200302_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='time',
        ),
        migrations.AddField(
            model_name='record',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime'),
            preserve_default=False,
        ),
    ]
