# Generated by Django 3.0.3 on 2020-03-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200302_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Cancel reason'),
        ),
        migrations.AddField(
            model_name='record',
            name='rollback_prepayment',
            field=models.NullBooleanField(default=None, verbose_name='Rollback prepayment'),
        ),
    ]
