# Generated by Django 3.0.3 on 2020-03-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200228_1216'),
        ('records', '0005_auto_20200304_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='accounts.Profile', verbose_name='Performer'),
        ),
    ]
