# Generated by Django 3.0.3 on 2020-03-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200228_1216'),
        ('records', '0007_auto_20200306_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to='accounts.Profile', verbose_name='Created by'),
        ),
    ]
