# Generated by Django 3.0.3 on 2020-03-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20200306_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerecordpayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='employeerecordpayment',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='employeerecordpayment',
            name='employee',
        ),
    ]
