# Generated by Django 3.0.3 on 2020-03-10 09:37

import django.core.validators
from django.db import migrations
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20200309_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepayment',
            name='value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0.01, currency='UAH'))], verbose_name='Value'),
        ),
    ]
