# Generated by Django 3.0.3 on 2020-02-28 12:16

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('parlors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parlor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='parlors.Parlor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='fine',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fine', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='fine',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='accounts.Profile', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='fine',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_fine', to=settings.AUTH_USER_MODEL, verbose_name='Status changed by'),
        ),
        migrations.AddField(
            model_name='fine',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='core.FineType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bounty', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty', to='accounts.Profile', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_bounty', to=settings.AUTH_USER_MODEL, verbose_name='Status changed by'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties', to='core.BountyType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='weekend',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['date'], name='accounts_we_date_0bab46_brin'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'parlor')},
        ),
        migrations.AddIndex(
            model_name='fine',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='accounts_fi_created_f892ed_brin'),
        ),
        migrations.AddIndex(
            model_name='bounty',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='accounts_bo_created_9c6010_brin'),
        ),
    ]
