# Generated by Django 3.0.3 on 2020-03-10 09:37

import django.core.validators
from django.db import migrations
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200228_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0.01, 'UAH'))], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0.01, 'UAH'))], verbose_name='Amount'),
        ),
    ]
