# Generated by Django 3.0.3 on 2020-03-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20200228_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
    ]
