# Generated by Django 3.0.3 on 2020-03-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'expense type',
                'verbose_name_plural': 'expense types',
            },
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='approximate_time',
            field=models.TimeField(default='01:00', verbose_name='Примерное время на сеанс'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='only_one_per_master',
            field=models.BooleanField(default=True, help_text='\n            Если включить эту опцию - нельзя будет начать второй сеанс при активном сеанса этого типа.\n        ', verbose_name='Только один сеанс на мастера?'),
        ),
    ]
