# Generated by Django 3.0.3 on 2020-03-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200310_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
    ]
