# Generated by Django 3.0.3 on 2020-02-28 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20200228_1216'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motivations', '0001_initial'),
        ('core', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemotivation',
            name='sell_category',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Category', verbose_name='Sell category'),
        ),
        migrations.AddField(
            model_name='storemotivation',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='sessionmotivation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_motivations', to='accounts.Profile', verbose_name='Motivation'),
        ),
        migrations.AddField(
            model_name='sessionmotivation',
            name='session_type',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='session_types', to='core.SessionType', verbose_name='Session type'),
        ),
        migrations.AddField(
            model_name='sessionmotivation',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_types', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='educationmotivation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_motivations', to='accounts.Profile', verbose_name='Motivation'),
        ),
        migrations.AddField(
            model_name='educationmotivation',
            name='session_type',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='core.SessionType', verbose_name='Session type'),
        ),
        migrations.AddField(
            model_name='educationmotivation',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='defaultstoremotivation',
            name='sell_category',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Category', verbose_name='Sell category'),
        ),
        migrations.AddField(
            model_name='defaultsessionmotivation',
            name='session_type',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='default_motivations', to='core.SessionType', verbose_name='Session type'),
        ),
        migrations.AddField(
            model_name='defaulteducationmotivation',
            name='session_type',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='default_educations', to='core.SessionType', verbose_name='Education type'),
        ),
        migrations.AlterUniqueTogether(
            name='storemotivation',
            unique_together={('employee', 'sell_category')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionmotivation',
            unique_together={('employee', 'session_type')},
        ),
        migrations.AlterUniqueTogether(
            name='educationmotivation',
            unique_together={('employee', 'session_type')},
        ),
        migrations.AlterUniqueTogether(
            name='defaultstoremotivation',
            unique_together={('role', 'sell_category')},
        ),
        migrations.AlterUniqueTogether(
            name='defaultsessionmotivation',
            unique_together={('role', 'session_type')},
        ),
        migrations.AlterUniqueTogether(
            name='defaulteducationmotivation',
            unique_together={('role', 'session_type')},
        ),
    ]
