# Generated by Django 3.0.3 on 2020-02-28 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parlor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number')),
                ('certificate_prefix', models.CharField(help_text="Max 8 symbols. E.g. if prefix is equal to 'UA', certificate number will be like: UA000001.", max_length=8, verbose_name='Certificate prefix')),
            ],
            options={
                'verbose_name': 'parlor',
                'verbose_name_plural': 'parlors',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('transaction_code', models.UUIDField(default=uuid.uuid4, verbose_name='Transaction code')),
                ('transaction_type', models.CharField(choices=[('withdraw', 'Withdraw'), ('deposit', 'Deposit')], db_index=True, max_length=32, verbose_name='Transaction type')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('UAH', 'UAH ₴')], default='UAH', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Amount')),
                ('entity_id', models.PositiveIntegerField()),
                ('reference', models.TextField(blank=True, verbose_name='Reference')),
                ('created_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parlors_transaction', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parlors_transaction', to='contenttypes.ContentType')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='parlors.Parlor', verbose_name='Parlor')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
    ]
