# Generated by Django 3.0.3 on 2020-03-10 12:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parlors', '0001_initial'),
        ('core', '0002_auto_20200310_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('UAH', 'UAH ₴')], default='UAH', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0.01, 'UAH'))], verbose_name='Amount')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('image', models.ImageField(blank=True, null=True, upload_to='expenses', verbose_name='Image')),
                ('created_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('parlor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='parlors.Parlor', verbose_name='Parlor')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.ExpenseType', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
            },
        ),
    ]
